server {
    listen 80;
    server_name _;
    root /var/www/html;

    index index.php index.html index.htm;

    location / {
        # 尝试匹配文件或目录，如果找不到则回退到 index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # 将请求传递给 PHP-FPM
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        # 拒绝访问 .htaccess 文件
        deny all;
    }

    # 为静态文件添加缓存头
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
      expires 1M;
      access_log off;
      add_header Cache-Control "public";
    }

    # 为字体文件添加缓存头
    location ~* \.(?:woff|woff2|ttf|eot)$ {
      expires 1M;
      access_log off;
      add_header Cache-Control "public";
    }
}